### ISSUE TITLE
Please, Enable Discussions

### ISSUE THREAD

**Issue by tajmone** [wshito/asciidoctor-chunker#26]
@wshito, I've finally managed to start using asciidoctor-chunker, and I'm very impressed by the results! Now that at the [ALAN-Docs] project we've reached the production stage of one of our books, we'll be using this excellent tool to create a chunked version (most likely, for an executable eBook for offline reading).

If you could enable **Discussion** on the repository, we'd be happy to share links to any publications that will use asciidoctor-chunker. Also, enabling Discussions would allow to ask questions, discuss ideas, etc., without cluttering the repository Issues (which could then be used just for development tasks).

[ALAN-Docs]: https://github.com/alan-if/alan-docs

**Comment by wshito** [comment]
Hi, there.  I prefer discussing on the Issues since the community is still small.  Actually, I've never used Discussions page in my private repositories working with other developers, so I am a little biased.

Honestly speaking, I'm just afraid I loose incentives to follow the discussions since they don't need to be closed.  I'm pretty sure that I'll be lazy to check the separate pages to go back and forth to collect informations regarding to a single issue.

I might change my mind as the community grows bigger.  But at the moment, please use issues for discussions.
